trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - /pipelines/Dfe.Spi.Common.Context.yml
      - /src/Dfe.Spi.Common/Dfe.Spi.Common.Context/*
pool:
    vmImage: 'ubuntu-latest'

variables:
    BuildConfiguration: Release

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.9.1'
    inputs:
      versionSpec: '4.9.1'

  - task: NuGetCommand@2
    displayName: 'Restore Public & Private NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'c5095ddb-6433-4990-a3a5-1df8a78b1302/$(FeedSecret)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Library'
    inputs:
      command: 'build'
      projects: 'src/Dfe.Spi.Common/Dfe.Spi.Common.Context/Dfe.Spi.Common.Context.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Pack Library'
    inputs:
      command: 'pack'
      packagesToPack: 'src/Dfe.Spi.Common/Dfe.Spi.Common.Context/Dfe.Spi.Common.Context.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'