trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - /pipelines/Dfe.Spi.Common.Http.Server.yml
      - /src/Dfe.Spi.Common/Dfe.Spi.Common.Http.Server/*
pool:
    vmImage: 'ubuntu-latest'

variables:
    BuildConfiguration: Release

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 6.4.0'
    inputs:
      versionSpec: '6.4.0'

  - task: NuGetCommand@2
    displayName: 'Restore Public & Private NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'c5095ddb-6433-4990-a3a5-1df8a78b1302/$(FeedSecret)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Common Http Server Library'
    inputs:
      command: 'build'
      projects: 'src/Dfe.Spi.Common/Dfe.Spi.Common.Http.Server/Dfe.Spi.Common.Http.Server.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests'
    inputs:
      command: test
      projects: 'src/Dfe.Spi.Common/Dfe.Spi.Common.Http.Server.UnitTests/Dfe.Spi.Common.Http.Server.UnitTests.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'
      
  - task: DotNetCoreCLI@2
    displayName: 'Pack Common Http Server Library'
    inputs:
      command: 'pack'
      packagesToPack: 'src/Dfe.Spi.Common/Dfe.Spi.Common.Http.Server/Dfe.Spi.Common.Http.Server.csproj'
      nobuild: true
      versioningScheme: 'off'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'