trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - /pipelines/Dfe.Spi.Common.SharedAzure.yml
      - /common-azure/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.7.1'
    inputs:
      versionSpec: '4.7.1'

  - task: CopyFiles@2
    displayName: 'Copy ARM template'
    inputs:
      Contents: |
        common-azure/*
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'