
trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - /pipelines/Dfe.Spi.Common.Extensions.yml
      - /src/Dfe.Spi.Common/Dfe.Spi.Common.Extensions/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.7.1'
    inputs:
      versionSpec: '4.7.1'

  - task: NuGetCommand@2
    displayName: 'Restore Public & Private NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'c5095ddb-6433-4990-a3a5-1df8a78b1302/$(FeedSecret)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Common Extensions Library'
    inputs:
      command: 'build'
      projects: 'src/Dfe.Spi.Common/Dfe.Spi.Common.Extensions/Dfe.Spi.Common.Extensions.csproj'
      arguments: '--configuration Release --output $(Build.BinariesDirectory) --no-restore'
      
  - task: CopyFiles@2
    displayName: 'Copy NuGet Package to Artifacts Staging'
    inputs:
      SourceFolder: '$(Build.BinariesDirectory)'
      Contents: 'Dfe.Spi.Common.Extensions.*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'